apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartlink-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smartlink
  template:
    metadata:
      labels:
        app: smartlink
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9700"        # <-- match the real port of your app
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: smartlink
          image: fasj/smartlink:latest
          ports:
            - containerPort: 9700
          envFrom:
            - secretRef:
                name: smartlink-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
